import React, { useState } from "react";
import styles from "./Tasks.module.css";

// Mock the AI service call
const generateFocusPlanService = (tasks: { title: string }[]) => {
    console.log("[MOCK] Sending tasks to AI:", tasks);

    const mockPlan = `
**Focus Plan Generated by AI**

**Primary Goal:** Complete the project efficiently.

1.  **Phase 1: Frontend Finalization (2 hours)**
    * **Task:** Finish React frontend
    * **Focus:** UI Polish and final state connections.

2.  **Phase 2: Backend Development (3 hours)**
    * **Task:** Write backend controllers
    * **Focus:** Implement CRUD operations for tasks and user data.

3.  **Phase 3: Quality Assurance (1 hour)**
    * **Task:** Test AI focus plan
    * **Focus:** Integration testing and deployment readiness checks.

**Total Estimated Time:** 6 hours
`;
    const success = Math.random() > 0.1;

    return new Promise((resolve, reject) => {
        setTimeout(() => {
            if (success) {
                resolve({ plan: mockPlan });
            } else {
                reject({ message: "Service temporarily unavailable." });
            }
        }, 1500);
    });
};

// Focus Plan Component
export default function FocusPlan() {
    const [text, setText] = useState(
        "Finish React frontend\nWrite backend controllers\nTest AI focus plan"
    );
    const [plan, setPlan] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const gen = async () => {
        setLoading(true);
        setError(null);
        setPlan(null);

        const tasks = text.split("\n").filter(Boolean).map((t) => ({ title: t.trim() }));

        try {
            const res: any = await generateFocusPlanService(tasks);
            setPlan(res.plan || res.data?.plan || JSON.stringify(res));
        } catch (err: any) {
            console.error("AI Generation Failed:", err);
            setError(err?.message || "AI Failed! Could not generate plan.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className={styles.taskPage}>
            {/* Header */}
            <h2 style={{ color: '#667eea', marginBottom: '2rem', fontSize: '2rem', fontWeight: 'bold' }}>
                🎯 Focus Plan
            </h2>

            {/* Main Content Card */}
            <div className={styles.taskForm} style={{ maxWidth: '100%' }}>
                <div style={{ marginBottom: 24 }}>
                    <label className={styles.modalLabel}>📝 Your Tasks</label>
                    <textarea
                        className={styles.focusPlanTextarea}
                        rows={6}
                        value={text}
                        onChange={(e) => setText(e.target.value)}
                        placeholder="Enter tasks, one per line... (e.g., Finish React frontend, Write backend controllers, etc.)"
                    />
                    <p style={{ fontSize: '0.85rem', color: '#718096', marginTop: '8px' }}>
                        Enter one task per line. AI will create an optimized focus plan.
                    </p>
                </div>

                {/* Generate Button */}
                <button 
                    className={styles.btnFocusGenerate}
                    onClick={gen} 
                    disabled={loading}
                >
                    {loading ? (
                        <>⏳ Generating Plan...</>
                    ) : (
                        <>✨ Generate AI Focus Plan</>
                    )}
                </button>

                {/* Error Message */}
                {error && (
                    <div className={styles.errorBox}>
                        <span>❌ {error}</span>
                    </div>
                )}

                {/* Generated Plan */}
                {plan && (
                    <div className={styles.planOutput}>
                        <h3 className={styles.planTitle}>📋 Your Focus Plan</h3>
                        <pre className={styles.planContent}>
                            {plan}
                        </pre>
                    </div>
                )}
            </div>
        </div>
    );
}